apiVersion: v1
kind: Pod
metadata:
  name:  kerasac-pod
  namespace: annashch
spec:
      containers:
        - name: gpu-container
          image: kundajelab/adpd_pseudobulk_nautilus:latest
          args: ["sleep","36500000"]
          resources:
            limits:
              memory: 8Gi
              cpu: 2
              nvidia.com/gpu: 1
            requests:
              memory: 8Gi
              cpu: 2
              nvidia.com/gpu: 1     
          volumeMounts:
            - mountPath: /data
              name: adpdpvc2
      restartPolicy: Never
      volumes:
        - name: adpdpvc2
          persistentVolumeClaim:
            claimName: adpdpvc2

