apiVersion: batch/v1
kind: Job
metadata: 
 name: adpd-regression
spec: 
 template: 
  spec: 
   containers: 
    - name: adpd-regression-container
      image: kundajelab/adpd_pseudobulk_nautilus:latest
      command: ["bash","/root/alzheimers_parkinsons/nautilus_cv_pseudobulk/cross_validate.classification.gc.sh"]
      args: ["4", "0", "4","5","6"]
      volumeMounts:
      - name: storage-pod
        mountPath: /data
      resources: 
        limits: 
          memory: 60Gi
          cpu: 15
          nvidia.com/gpu: 1
        requests: 
          memory: 50Gi
          cpu: 10
          nvidia.com/gpu: 1
   volumes:
    - name: storage-pod
      persistentVolumeClaim:
        claimName: adpdpvc2
   restartPolicy: Never
 backoffLimit: 1
