apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adpdpvc2
spec:
    storageClassName: rook-cephfs
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: 500Gi

